### ISSUE TITLE
znaytu zobrazhennya

### ISSUE THREAD

**Issue by oliver1117** [oliver1117/project_x#1]
znaytu zobrazhennya NRPK i vidzvityvatu

**Comment by MaryanaMynda** [comment]
https://www.google.com.ua/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiAuLK_mMXXAhXlAJoKHXXOCgMQjRwIBw&url=http%3A%2F%2Fnovyy-rozdil.wikimapia.org%2Fphotos%2F&psig=AOvVaw1E_dHKqz109VKJwK6T-s8X&ust=1510993746687631

**Comment by MaryanaMynda** [comment]
https://github.com/MaryanaMynda/test_project/invitations
